#!/usr/bin/bash                                                                                      

#/usr/local/bin/genvimspectorconfig

#touch .vimspector.json                                                                               
cat << "EOF" > .vimspector.json                                                                        
{                                                                                                    
  "configurations": {                                                                                
    "run": {                                                                                         
     "adapter": "vscode-go",                                                                        
     "configuration": {                                                                             
       "request": "launch",                                                                         
       "program": "${fileDirname}",                                                                 
       "mode": "debug",                                                                             
       "dlvToolPath": "$HOME/go/bin/dlv"     }                                                      
    }                                                                                                
  }                                                                                                  
}                                                                                                    
EOF
